### ISSUE TITLE
Bad control character in Recommendation_System.ipynb

### ISSUE THREAD

**Issue by simon9k** [SpencerPao/Data_Science#4]
### Just missed a quotation mark, this file is broken now.

Recommendation_System.ipynb
The editor could not be opened due to an unexpected error: Bad control character in string literal in JSON at position 40530 (line 1054 column 54) due to your latest update

Thanks for your great tutorials.

**Comment by SpencerPao** [comment]
Thank you for noticing that! I fixed and push to main branch.
